const links = [
    {"title": "Acer", "description": "Laptops, desktops, and accessories", "url": "https://www.acer.com"},
    {"title": "Adidas", "description": "Sportswear and shoes", "url": "https://www.adidas.com"},
    {"title": "Alibaba", "description": "Online marketplace", "url": "https://www.alibaba.com"},
    {"title": "AliExpress", "description": "Online shopping", "url": "https://www.aliexpress.com"},
    {"title": "AllMusic", "description": "Music database and community", "url": "https://www.allmusic.com"},
    {"title": "Amazon", "description": "Online shopping", "url": "https://www.amazon.com"},
    {"title": "Ancestry", "description": "Genealogy and family history", "url": "https://www.ancestry.com"},
    {"title": "Anthropologie", "description": "Clothing, accessories, and home decor", "url": "https://www.anthropologie.com"},
    {"title": "AP News", "description": "Breaking news and headlines", "url": "https://www.apnews.com"},
    {"title": "Apple", "description": "Electronics and technology company", "url": "https://www.apple.com"},
    {"title": "Armani", "description": "Luxury fashion brand", "url": "https://www.armani.com"},
    {"title": "ASOS", "description": "Online fashion retailer", "url": "https://www.asos.com"},
    {"title": "ASRock", "description": "Computer hardware manufacturer", "url": "https://www.asrock.com"},
    {"title": "ASUS", "description": "Computer hardware and electronics", "url": "https://www.asus.com"},
    {"title": "Athleta", "description": "Women's activewear and workout clothes", "url": "https://www.athleta.com"},
    {"title": "Audio-Technica", "description": "Audio equipment manufacturer", "url": "https://www.audio-technica.com"},
    {"title": "Banana Republic", "description": "Clothing and accessories retailer", "url": "https://www.bananarepublic.com"},
    {"title": "Bang & Olufsen", "description": "High-end audio equipment manufacturer", "url": "https://www.bang-olufsen.com"},
    {"title": "Belkin", "description": "Computer and phone accessories", "url": "https://www.belkin.com"},
    {"title": "Best Buy", "description": "Electronics retailer", "url": "https://www.bestbuy.com"},
    {"title": "B&H Photo Video", "description": "Electronics retailer", "url": "https://www.bhphotovideo.com"},
    {"title": "Biostar", "description": "Computer hardware manufacturer", "url": "https://www.biostar.com"},
    {"title": "Bitbucket", "description": "Code collaboration platform", "url": "https://www.bitbucket.org"},
    {"title": "Bloomberg", "description": "Financial news and data", "url": "https://www.bloomberg.com"},
    {"title": "Bloomingdale's", "description": "Department store chain", "url": "https://www.bloomingdales.com"},
    {"title": "Box", "description": "Cloud storage and collaboration platform", "url": "https://www.box.com"},
    {"title": "Box Office Mojo", "description": "Box office reporting website", "url": "https://www.boxofficemojo.com"},
    {"title": "Boohoo", "description": "Fashion retailer", "url": "https://www.boohoo.com"},
    {"title": "Bottega Veneta", "description": "Luxury fashion brand", "url": "https://www.bottegaveneta.com"},
    {"title": "Bowers & Wilkins", "description": "Audio equipment manufacturer", "url": "https://www.bowers-wilkins.com"},
    {"title": "Breitling", "description": "Luxury watchmaker", "url": "https://www.breitling.com"},
    {"title": "Encyclopaedia Britannica", "description": "General knowledge encyclopedia", "url": "https://www.britannica.com"},
    {"title": "Bulgari", "description": "Luxury jewelry and accessories", "url": "https://www.bulgari.com"},
    {"title": "Burberry", "description": "Luxury fashion brand", "url": "https://www.burberry.com"},
    {"title": "Business Insider", "description": "Business news website", "url": "https://www.businessinsider.com"},
    {"title": "BuzzFeed", "description": "Digital media company", "url": "https://www.buzzfeed.com"},
    {"title": "BuzzFeed News", "description": "News division of BuzzFeed", "url": "https://www.buzzfeednews.com"},
    {"title": "Canon", "description": "Camera and printer manufacturer", "url": "https://www.canon.com"},
    {"title": "Cartier", "description": "Luxury jewelry and watches", "url": "https://www.cartier.com"},
    {"title": "CBS News", "description": "News division of CBS", "url": "https://www.cbsnews.com"},
    {"title": "Chanel", "description": "Luxury fashion brand", "
